"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUp, CalendarDays, CalendarPlus, ChevronDown, Copy, Heart, MapPin, Music2, Pause, Play, Send, Sparkles, Video } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { InvitationMedia } from "./invitation-media";

interface CinematicInvitationProps {
  brideName: string;
  groomName: string;
  weddingAt: string;
  venueName: string | null;
  invitationMessage: string | null;
  story: string | null;
  brideImage: string | null;
  groomImage: string | null;
  gallery: Array<{ id: string; storage_path: string }>;
  mapUrl: string | null;
  musicUrl: string | null;
  coverImage: string | null;
  events: Array<{ id: string; title: string; starts_at: string; venue_name: string | null; map_url: string | null }>;
  id: string; brideOccupation: string | null; groomOccupation: string | null; brideParents: string | null; groomParents: string | null; brideBio: string | null; groomBio: string | null; familyInvitationMessage: string | null; videoUrl: string | null; rsvpEmail: string | null; whatsappNumber: string | null;
}

const wordMotion = { hidden: { opacity: 0, y: 35, filter: "blur(8px)" }, visible: { opacity: 1, y: 0, filter: "blur(0px)" } };

export function CinematicInvitation(props: CinematicInvitationProps) {
  const [opened, setOpened] = useState(false);
  const [playing, setPlaying] = useState(false);
  const [musicPrompt, setMusicPrompt] = useState(Boolean(props.musicUrl));
  const [attendance, setAttendance] = useState<"attending" | "declined">("attending"); const [rsvpNotice, setRsvpNotice] = useState(""); const [pageUrl, setPageUrl] = useState("");
  const [now, setNow] = useState(() => Date.now());
  const reduceMotion = useReducedMotion();
  const audio = useRef<HTMLAudioElement>(null);
  const date = new Intl.DateTimeFormat("en-IN", { dateStyle: "full", timeStyle: "short" }).format(new Date(props.weddingAt));
  const remaining = Math.max(0, new Date(props.weddingAt).getTime() - now);
  const days = Math.floor(remaining / 86_400_000);
  const hours = Math.floor((remaining % 86_400_000) / 3_600_000);

  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => setPageUrl(location.href), []);
  const openWithMusic = () => { void audio.current?.play().catch(() => setPlaying(false)); setMusicPrompt(false); };
  const toggleMusic = () => { if (!audio.current) return; if (audio.current.paused) void audio.current.play(); else audio.current.pause(); };
  const submitRsvp = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const name = String(new FormData(event.currentTarget).get("name") || "").trim(); if (!name) return setRsvpNotice("Please enter your name."); const message = `${name} ${attendance === "attending" ? "will joyfully attend" : "will be unable to attend"} ${props.brideName} & ${props.groomName}'s wedding.`; const phone = props.whatsappNumber?.replace(/\D/g, ""); if (phone) { window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); return setRsvpNotice("Your RSVP is ready to send on WhatsApp."); } if (props.rsvpEmail) { location.href = `mailto:${props.rsvpEmail}?subject=${encodeURIComponent(`Wedding RSVP from ${name}`)}&body=${encodeURIComponent(message)}`; return setRsvpNotice("Your email app is opening with your RSVP."); } setRsvpNotice("The hosts have not added an RSVP contact yet."); };

  return <main className="min-h-screen overflow-hidden bg-[#110e0d] text-[#f9f1e8] selection:bg-[#d6af7c] selection:text-[#211613]">
    {props.musicUrl && <audio ref={audio} loop src={props.musicUrl} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} />}
    <div className="pointer-events-none fixed inset-0 opacity-70 [background:radial-gradient(circle_at_18%_15%,#704a3c88,transparent_25%),radial-gradient(circle_at_88%_76%,#9b745866,transparent_28%),linear-gradient(135deg,#110e0d,#221815_58%,#110e0d)]" />
    {!reduceMotion && <div className="pointer-events-none fixed inset-0 opacity-30 [background-image:radial-gradient(#f5d9b322_1px,transparent_1px)] [background-size:38px_38px]" />}
    {musicPrompt && <div className="cinematic-music-gate"><div><Music2 size={22} /><p>{props.brideName} <i>&amp;</i> {props.groomName}</p><span>Set the mood for this story.</span><button onClick={openWithMusic}><Play size={14} fill="currentColor" /> Open with music</button><button className="quiet" onClick={() => setMusicPrompt(false)}>Continue without music</button></div></div>}
    {props.musicUrl && <button aria-label={playing ? "Mute background music" : "Play background music"} className="fixed right-5 top-5 z-30 grid h-11 w-11 place-items-center rounded-full border border-[#f6d4a955] bg-[#1e1613cc] backdrop-blur" onClick={toggleMusic}>{playing ? <Pause size={16} /> : <Music2 size={17} />}</button>}
    <button aria-label="Back to top" className="fixed bottom-5 right-5 z-30 grid h-11 w-11 place-items-center rounded-full border border-[#f6d4a955] bg-[#1e1613cc] backdrop-blur" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><ArrowUp size={17} /></button>
    <section className="relative grid min-h-[100svh] place-items-center px-6 py-24 text-center">{props.coverImage && <img alt="Wedding celebration" className="absolute inset-0 h-full w-full object-cover opacity-25" src={props.coverImage} />}<div className="absolute inset-0 bg-[#110e0d]/55" /><motion.div className="cinematic-curtain cinematic-curtain-left" initial={{ scaleY: 1 }} animate={{ scaleY: musicPrompt ? 1 : 0 }} transition={{ duration: reduceMotion ? 0 : 1.25, ease: [0.76, 0, 0.24, 1] }} /><motion.div className="cinematic-curtain cinematic-curtain-right" initial={{ scaleY: 1 }} animate={{ scaleY: musicPrompt ? 1 : 0 }} transition={{ duration: reduceMotion ? 0 : 1.25, ease: [0.76, 0, 0.24, 1] }} />
      <motion.div animate={reduceMotion ? undefined : { rotate: 360 }} transition={{ duration: 80, repeat: Infinity, ease: "linear" }} className="absolute h-[min(80vw,580px)] w-[min(80vw,580px)] rounded-full border border-[#d6af7c22]" />
      <motion.div animate={reduceMotion ? undefined : { rotate: -360, scale: [1, 1.05, 1] }} transition={{ duration: 60, repeat: Infinity, ease: "linear" }} className="absolute h-[min(64vw,440px)] w-[min(64vw,440px)] rounded-full border border-[#d6af7c22]" />
      <motion.div initial="hidden" animate={musicPrompt ? "hidden" : "visible"} transition={{ staggerChildren: 0.18, delayChildren: reduceMotion ? 0 : .92 }} className="relative max-w-4xl">
        <motion.p variants={wordMotion} transition={{ duration: 0.8 }} className="text-[10px] font-semibold uppercase tracking-[0.46em] text-[#e4c495] sm:text-xs">An intimate celebration</motion.p>
        <motion.div variants={wordMotion} transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }} className="mt-10 font-serif text-[clamp(4rem,13vw,10rem)] leading-[0.78] tracking-tight"><span className="block">{props.brideName}</span><span className="my-5 block font-sans text-[0.2em] font-light italic text-[#d6af7c]">and</span><span className="block">{props.groomName}</span></motion.div>
        <motion.div variants={wordMotion} transition={{ duration: 0.8 }} className="mx-auto mt-12 max-w-lg"><p className="leading-8 text-[#ddcbbd]">{props.invitationMessage || "A story, written in a thousand quiet moments, now opens into a lifetime."}</p><button className="mt-10 inline-flex items-center gap-2 rounded-full border border-[#e5c18c88] px-6 py-3 text-xs font-semibold uppercase tracking-[0.18em] transition hover:bg-[#e5c18c] hover:text-[#1a100d]" onClick={() => setOpened(true)}><Sparkles size={15} /> Open the invitation</button></motion.div>
      </motion.div>
      <ChevronDown className="absolute bottom-7 animate-bounce text-[#d6af7c]" size={20} />
    </section>
    <AnimatePresence>{opened && <motion.section animate={{ opacity: 1 }} initial={{ opacity: 0 }} className="relative mx-auto grid max-w-5xl gap-14 px-6 py-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-semibold uppercase tracking-[0.32em] text-[#d6af7c]">Save the date</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-6xl">A night made for forever.</h2><p className="mt-7 max-w-xl leading-8 text-[#ddcbbd]">{props.story || "We would be honoured to have you beside us as we gather, celebrate, and begin our next chapter."}</p></motion.div><motion.div initial={{ opacity: 0, scale: 0.94 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} className="rounded-[2rem] border border-[#e5c18c33] bg-[#f8e8d50b] p-7 backdrop-blur-md"><div className="flex gap-3 text-[#d6af7c]"><CalendarDays size={19} /><p className="text-sm font-semibold uppercase tracking-[0.15em]">{date}</p></div>{props.venueName && <div className="mt-6 flex gap-3 text-[#d6af7c]"><MapPin size={19} /><p className="text-sm font-semibold uppercase tracking-[0.15em]">{props.venueName}</p></div>}<div className="mt-10 grid grid-cols-2 gap-3"><CountBox label="Days" value={days} /><CountBox label="Hours" value={hours} /></div><p className="mt-7 flex items-center gap-2 text-sm text-[#ddcbbd]"><Heart size={14} fill="currentColor" className="text-[#d6af7c]" /> Your presence is our favourite gift.</p></motion.div></motion.section>}</AnimatePresence>
    {props.events.length > 0 && <section className="relative mx-auto max-w-6xl px-6 py-24 text-center"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#d6af7c]">The celebration</p><h2 className="mt-4 font-serif text-4xl">Our wedding journey</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{props.events.map((event, index) => <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .1 }} className="rounded-3xl border border-[#e5c18c33] bg-[#f8e8d50b] p-6 text-left" key={event.id}><span className="text-[#d6af7c]">0{index + 1}</span><h3 className="mt-4 font-serif text-2xl">{event.title}</h3><p className="mt-3 text-sm leading-6 text-[#ddcbbd]">{new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long", hour: "numeric", minute: "2-digit" }).format(new Date(event.starts_at))}</p>{event.venue_name && <p className="mt-2 text-sm text-[#ddcbbd]">{event.venue_name}</p>}{event.map_url && <a className="mt-5 inline-block text-xs font-semibold uppercase tracking-[.14em] text-[#d6af7c]" href={event.map_url} target="_blank" rel="noreferrer">Directions →</a>}</motion.article>)}</div></section>}
    <section className="relative mx-auto max-w-5xl px-6 py-24 text-center"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#d6af7c]">Meet the couple</p><h2 className="mt-4 font-serif text-4xl">Two stories, one forever</h2><div className="mt-10 grid gap-8 md:grid-cols-2"><CinematicProfile image={props.groomImage} name={props.groomName} role="Son of" parents={props.groomParents} detail={props.groomOccupation || props.groomBio} /><CinematicProfile image={props.brideImage} name={props.brideName} role="Daughter of" parents={props.brideParents} detail={props.brideOccupation || props.brideBio} /></div></section>
    <InvitationMedia brideImage={props.brideImage} brideName={props.brideName} dark gallery={props.gallery} groomImage={props.groomImage} groomName={props.groomName} mapUrl={props.mapUrl} musicUrl={null} venueName={props.venueName} />
    {props.videoUrl && <section className="relative px-6 py-24 text-center"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#d6af7c]">Our story</p><h2 className="mt-4 font-serif text-4xl">A special glimpse</h2><div className="mx-auto mt-10 aspect-video max-w-4xl overflow-hidden rounded-3xl border border-[#e5c18c55]"><iframe className="h-full w-full border-0" src={youtubeEmbed(props.videoUrl)} title="Wedding story video" allowFullScreen /></div></section>}
    <section className="relative px-6 py-24 text-center"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#d6af7c]">Celebrate with us</p><h2 className="mt-4 font-serif text-4xl">Will you join us?</h2><form onSubmit={submitRsvp} className="mx-auto mt-10 max-w-xl rounded-3xl border border-[#e5c18c33] bg-[#f8e8d50b] p-5 text-left backdrop-blur"><div className="grid gap-3 sm:grid-cols-2"><button className={`rounded-xl border p-4 text-sm ${attendance === "attending" ? "border-[#d6af7c] bg-[#d6af7c] text-[#211613]" : "border-[#e5c18c44]"}`} type="button" onClick={() => setAttendance("attending")}>With joy, I will be there</button><button className={`rounded-xl border p-4 text-sm ${attendance === "declined" ? "border-[#d6af7c] bg-[#d6af7c] text-[#211613]" : "border-[#e5c18c44]"}`} type="button" onClick={() => setAttendance("declined")}>With regret, I cannot</button></div><label className="mt-5 block text-xs font-semibold uppercase tracking-[.15em] text-[#d6af7c]">Your name<input required name="name" className="mt-2 block w-full rounded-xl border border-[#e5c18c44] bg-black/20 px-4 py-3 text-base normal-case tracking-normal text-white" placeholder="Enter your name" /></label><div className="mt-5 grid gap-3 sm:grid-cols-2"><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#d6af7c] px-4 py-3 text-xs font-bold uppercase tracking-[.1em] text-[#211613]" type="submit"><Send size={15} /> Send RSVP</button><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#e5c18c55] px-4 py-3 text-xs font-bold uppercase tracking-[.1em]" type="button" onClick={() => navigator.clipboard?.writeText(pageUrl).then(() => setRsvpNotice("Invitation link copied."))}><Copy size={15} /> Copy link</button><a className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#e5c18c55] px-4 py-3 text-xs font-bold uppercase tracking-[.1em]" href={`https://wa.me/?text=${encodeURIComponent(`${props.brideName} & ${props.groomName} invite you: ${pageUrl}`)}`} target="_blank" rel="noreferrer">Share WhatsApp</a><a className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#e5c18c55] px-4 py-3 text-xs font-bold uppercase tracking-[.1em]" href={`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`${props.brideName} & ${props.groomName} Wedding`)}&dates=${new Date(props.weddingAt).toISOString().replace(/[-:.]/g, "").slice(0, 15)}Z/${new Date(new Date(props.weddingAt).getTime() + 14400000).toISOString().replace(/[-:.]/g, "").slice(0, 15)}Z`} target="_blank" rel="noreferrer"><CalendarPlus size={15} /> Add calendar</a></div>{rsvpNotice && <p className="mt-4 text-center text-sm text-[#d6af7c]">{rsvpNotice}</p>}</form></section>
    <footer className="relative px-6 py-16 text-center"><div className="mx-auto h-px max-w-md bg-gradient-to-r from-transparent via-[#d6af7c88] to-transparent" /><p className="mt-9 font-serif text-3xl italic text-[#f2dcc3]">With love, always.</p><p className="mx-auto mt-4 max-w-xl leading-7 text-[#ddcbbd]">{props.familyInvitationMessage || "We await your gracious presence and blessings."}</p></footer>
  </main>;
}

function CountBox({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-[#e5c18c2b] bg-black/10 px-4 py-5 text-center"><p className="font-serif text-4xl text-[#f4e4d0]">{String(value).padStart(2, "0")}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.22em] text-[#d6af7c]">{label}</p></div>; }
function CinematicProfile({ image, name, role, parents, detail }: { image: string | null; name: string; role: string; parents: string | null; detail: string | null }) { return <motion.article initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-[2rem] border border-[#e5c18c33] bg-[#f8e8d50b] p-5"><div className="relative mx-auto aspect-[.85] max-w-xs overflow-hidden rounded-[1.5rem] border border-[#d6af7c77] bg-[#31201a]">{image ? <img src={image} alt={name} className="h-full w-full object-cover" /> : <span className="grid h-full place-items-center font-serif text-7xl text-[#d6af7c]">{name.slice(0, 1)}</span>}</div><h3 className="mt-5 font-serif text-3xl">{name}</h3><p className="mt-2 text-xs font-semibold uppercase tracking-[.18em] text-[#d6af7c]">{role}</p>{parents && <p className="mt-3 text-[#ddcbbd]">{parents}</p>}{detail && <p className="mt-2 text-sm leading-6 text-[#bda99a]">{detail}</p>}</motion.article>; }
function youtubeEmbed(url: string) { const match = url.match(/(?:youtu\.be\/|v=|embed\/)([^?&/]+)/); return match ? `https://www.youtube-nocookie.com/embed/${match[1]}` : url; }
