"use client";

import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUp, CalendarPlus, ChevronDown, Copy, MapPin, Music2, Pause, Play, Send, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { DesignerFooter } from "./designer-footer";

type Event = { id: string; title: string; starts_at: string; venue_name: string | null; map_url: string | null };
type GalleryImage = { id: string; storage_path: string };
type Props = { id: string; brideName: string; groomName: string; weddingAt: string; venueName: string | null; invitationMessage: string | null; story: string | null; events: Event[]; coverImage: string | null; brideImage: string | null; groomImage: string | null; gallery: GalleryImage[]; musicUrl: string | null; mapUrl: string | null; brideOccupation: string | null; groomOccupation: string | null; brideParents: string | null; groomParents: string | null; brideBio: string | null; groomBio: string | null; familyInvitationMessage: string | null; videoUrl: string | null; rsvpEmail: string | null; whatsappNumber: string | null };
const rise = { hidden: { opacity: 0, y: 36 }, show: { opacity: 1, y: 0 } };
const fmtDate = (date: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" }).format(new Date(date));
const fmtTime = (date: string) => new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(new Date(date));
const embedUrl = (url: string) => { const match = url.match(/(?:youtu\.be\/|v=|embed\/)([^?&/]+)/); return match ? `https://www.youtube-nocookie.com/embed/${match[1]}` : url; };
function Flourish() { return <div className="classic-flourish" aria-hidden="true"><span />❦<span /></div>; }
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <motion.header variants={rise} transition={{ duration: .75 }} className="classic-heading"><p>{eyebrow}</p><h2>{title}</h2>{copy && <div>{copy}</div>}<Flourish /></motion.header>; }
function ClassicSection({ children, className, id }: { children: React.ReactNode; className?: string; id?: string }) { const reduced = useReducedMotion(); return <motion.section id={id} className={`classic-section ${className ?? ""}`} initial={reduced ? false : "hidden"} whileInView="show" viewport={{ once: true, amount: .13 }} transition={{ staggerChildren: .13, delayChildren: .05 }}>{children}</motion.section>; }

export function ClassicInvitation(props: Props) {
  const [playing, setPlaying] = useState(false); const [musicPrompt, setMusicPrompt] = useState(Boolean(props.musicUrl)); const [now, setNow] = useState<number | null>(null); const [selectedImage, setSelectedImage] = useState<GalleryImage | null>(null); const audio = useRef<HTMLAudioElement>(null); const reduced = useReducedMotion();
  useEffect(() => { setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && setSelectedImage(null); addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, []);
  const delta = now === null ? 0 : Math.max(0, new Date(props.weddingAt).getTime() - now); const countdown = [["Days", Math.floor(delta / 86400000)], ["Hours", Math.floor(delta / 3600000) % 24], ["Minutes", Math.floor(delta / 60000) % 60], ["Seconds", Math.floor(delta / 1000) % 60]];
  const beginWithMusic = () => { void audio.current?.play().catch(() => setPlaying(false)); setMusicPrompt(false); }; const toggleMusic = () => { if (!audio.current) return; if (audio.current.paused) void audio.current.play(); else audio.current.pause(); };
  return <main className="classic-site">
    {props.musicUrl && <audio ref={audio} loop src={props.musicUrl} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} />}
    {musicPrompt && <div className="classic-music-prompt"><div><Music2 size={22} /><p>{props.brideName} <i>&amp;</i> {props.groomName}</p><span>A melody awaits. Choose how you would like to open the celebration.</span><button onClick={beginWithMusic}><Play size={14} fill="currentColor" /> Open with music</button><button className="quiet" onClick={() => setMusicPrompt(false)}>Continue without music</button></div></div>}
    {props.musicUrl && <button className="classic-sound" onClick={toggleMusic} aria-label={playing ? "Mute music" : "Play music"}>{playing ? <Pause size={16} /> : <Music2 size={16} />}</button>}
    <button className="classic-top" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Back to top"><ArrowUp size={17} /></button>
    <section className="classic-hero">{props.coverImage && <Image fill priority sizes="100vw" className="classic-cover" src={props.coverImage} alt="Wedding celebration background" />}<div className="classic-hero-wash" /><motion.div aria-hidden="true" className="classic-opening-panel classic-opening-left" initial={{ scaleX: 1 }} animate={{ scaleX: musicPrompt ? 1 : 0 }} transition={{ duration: reduced ? 0 : 1.35, delay: reduced ? 0 : .18, ease: [0.76, 0, 0.24, 1] }} /><motion.div aria-hidden="true" className="classic-opening-panel classic-opening-right" initial={{ scaleX: 1 }} animate={{ scaleX: musicPrompt ? 1 : 0 }} transition={{ duration: reduced ? 0 : 1.35, delay: reduced ? 0 : .18, ease: [0.76, 0, 0.24, 1] }} /><i className="classic-lotus classic-lotus-left">✾</i><i className="classic-lotus classic-lotus-right">✾</i><motion.div initial="hidden" animate={musicPrompt ? "hidden" : "show"} transition={{ staggerChildren: .14, delayChildren: reduced ? 0 : 1.05 }} className="classic-hero-content"><motion.div variants={rise} className="classic-bloom">❦</motion.div><motion.p variants={rise} className="classic-ganesha">ॐ शुभ विवाहम् ॐ</motion.p><motion.p variants={rise} className="classic-eyebrow">Together with their families</motion.p><motion.h1 variants={rise}><span>{props.brideName}</span><i>&amp;</i><span>{props.groomName}</span></motion.h1><motion.p variants={rise} className="classic-date">{fmtDate(props.weddingAt)} <b>·</b> {fmtTime(props.weddingAt)}</motion.p><motion.div variants={rise}><Flourish /></motion.div><motion.p variants={rise} className="classic-intro">{props.invitationMessage || "With joyful hearts, we invite you to celebrate the beginning of our forever."}</motion.p><motion.button variants={rise} className="classic-open" onClick={() => document.getElementById("classic-couple")?.scrollIntoView({ behavior: "smooth" })}>Open invitation <ChevronDown size={16} /></motion.button></motion.div></section>
    <ClassicSection id="classic-couple" className="classic-couple"><SectionTitle eyebrow="The couple" title="A union written in the stars" copy={props.story || "Two hearts, two families, and one beautiful new beginning."} /><div className="classic-couple-grid"><Person image={props.groomImage} name={props.groomName} role="Son of" parents={props.groomParents} detail={props.groomOccupation || props.groomBio} /><Person image={props.brideImage} name={props.brideName} role="Daughter of" parents={props.brideParents} detail={props.brideOccupation || props.brideBio} /></div></ClassicSection>
    {props.events.length > 0 && <ClassicSection className="classic-events"><SectionTitle eyebrow="Wedding journey" title="The sacred celebrations" copy="Join us for each cherished ritual and joyful gathering." /><div className="classic-event-path">{props.events.map((event, index) => <motion.article variants={rise} whileHover={reduced ? undefined : { y: -8 }} className="classic-event" key={event.id}><span>0{index + 1}</span><div className="classic-event-icon">{["✿", "☀", "✦", "❦"][index % 4]}</div><h3>{event.title}</h3><p>{new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long", hour: "numeric", minute: "2-digit" }).format(new Date(event.starts_at))}</p>{event.venue_name && <p>{event.venue_name}</p>}{event.map_url && <a href={event.map_url} target="_blank" rel="noreferrer">View map →</a>}</motion.article>)}</div></ClassicSection>}
    <ClassicSection className="classic-countdown"><SectionTitle eyebrow="Auspicious muhurat" title="Counting down to our day" /><div className="classic-count-grid">{countdown.map(([label, value]) => <motion.div variants={rise} key={String(label)}><strong>{String(value).padStart(2, "0")}</strong><span>{label}</span></motion.div>)}</div></ClassicSection>
    {props.gallery.length > 0 && <ClassicSection className="classic-gallery"><SectionTitle eyebrow="Before the vows" title="Little moments, forever memories" copy="Tap a photograph to pause in the moment." /><div className="classic-gallery-grid">{props.gallery.map((image, index) => <motion.button variants={rise} whileHover={reduced ? undefined : { y: -5, rotate: index % 2 ? 1 : -1 }} key={image.id} className={index === 0 ? "featured" : ""} onClick={() => setSelectedImage(image)}><Image fill sizes="(max-width: 650px) 100vw, 33vw" src={image.storage_path} alt="A wedding memory" /></motion.button>)}</div></ClassicSection>}
    {props.videoUrl && <ClassicSection className="classic-film"><SectionTitle eyebrow="Our story" title="A special glimpse" /><motion.div variants={rise} className="classic-video"><iframe src={embedUrl(props.videoUrl)} title="Wedding video" allowFullScreen /></motion.div></ClassicSection>}
    {(props.venueName || props.mapUrl) && <ClassicSection className="classic-venue"><SectionTitle eyebrow="Venue guide" title="Come celebrate with us" /><motion.div variants={rise} className="classic-venue-card"><MapPin size={25} /><h3>{props.venueName || "Wedding venue"}</h3><p>{fmtDate(props.weddingAt)} · {fmtTime(props.weddingAt)}</p>{props.mapUrl && <><iframe src={`https://www.google.com/maps?q=${encodeURIComponent(props.venueName || props.mapUrl)}&output=embed`} title="Wedding venue map" /><a href={props.mapUrl} target="_blank" rel="noreferrer">Get directions</a></>}</motion.div></ClassicSection>}
    <ClassicRsvp {...props} />
    <footer className="classic-footer"><Flourish /><p>With love, gratitude & blessings</p><h2>{props.brideName} <i>&amp;</i> {props.groomName}</h2><span>{fmtDate(props.weddingAt)}</span><b>{props.familyInvitationMessage || "We await your gracious presence and blessings."}</b><DesignerFooter /></footer>
    <AnimatePresence>{selectedImage && <motion.div className="classic-lightbox" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedImage(null)}><motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .94 }} onClick={event => event.stopPropagation()}><Image fill sizes="100vw" src={selectedImage.storage_path} alt="Wedding memory" /><button onClick={() => setSelectedImage(null)} aria-label="Close photo"><X /></button></motion.div></motion.div>}</AnimatePresence>
  </main>;
}
function Person({ image, name, role, parents, detail }: { image: string | null; name: string; role: string; parents: string | null; detail: string | null }) { return <motion.article variants={rise} whileHover={{ y: -8 }} className="classic-person"><div className="classic-portrait">{image ? <Image fill sizes="(max-width: 700px) 90vw, 35vw" src={image} alt={name} /> : <span>{name.slice(0, 1)}</span>}</div><i>✾</i><h3>{name}</h3><p>{role}</p>{parents && <b>{parents}</b>}{detail && <small>{detail}</small>}</motion.article>; }
function ClassicRsvp({ brideName, groomName, weddingAt, rsvpEmail, whatsappNumber }: Pick<Props, "brideName" | "groomName" | "weddingAt" | "rsvpEmail" | "whatsappNumber">) { const [attendance, setAttendance] = useState<"attending" | "declined">("attending"); const [notice, setNotice] = useState(""); const [url, setUrl] = useState(""); useEffect(() => setUrl(location.href), []); const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") || "").trim(); if (!name) return setNotice("Please enter your name."); const response = `${name} ${attendance === "attending" ? "will joyfully attend" : "will be unable to attend"} ${brideName} & ${groomName}'s wedding.`; const phone = whatsappNumber?.replace(/\D/g, ""); if (phone) { open(`https://wa.me/${phone}?text=${encodeURIComponent(response)}`, "_blank", "noopener,noreferrer"); return setNotice("Your RSVP is ready to send on WhatsApp."); } if (rsvpEmail) { location.href = `mailto:${rsvpEmail}?subject=${encodeURIComponent(`Wedding RSVP from ${name}`)}&body=${encodeURIComponent(response)}`; return setNotice("Your email app is opening with your RSVP."); } setNotice("The hosts have not added a WhatsApp number or email yet."); }; const copy = async () => { await navigator.clipboard?.writeText(url); setNotice("Invitation link copied."); }; return <ClassicSection className="classic-rsvp"><SectionTitle eyebrow="Bless us with your presence" title="Will you join the celebration?" copy="Let the couple know whether they can save a place for you." /><motion.form variants={rise} onSubmit={submit} className="classic-rsvp-card"><div><button type="button" className={attendance === "attending" ? "active" : ""} onClick={() => setAttendance("attending")}>With joy, I will be there</button><button type="button" className={attendance === "declined" ? "active" : ""} onClick={() => setAttendance("declined")}>With regret, I cannot</button></div><label>Your name<input required name="name" placeholder="Enter your name" /></label><div className="classic-rsvp-actions"><button type="submit"><Send size={15} /> Send RSVP</button><button type="button" onClick={copy}><Copy size={15} /> Copy link</button><a href={`https://wa.me/?text=${encodeURIComponent(`${brideName} & ${groomName} invite you to celebrate with them: ${url}`)}`} target="_blank" rel="noreferrer">Share WhatsApp</a><a href={`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`${brideName} & ${groomName} Wedding`)}&dates=${new Date(weddingAt).toISOString().replace(/[-:.]/g, "").slice(0, 15)}Z/${new Date(new Date(weddingAt).getTime() + 14400000).toISOString().replace(/[-:.]/g, "").slice(0, 15)}Z`} target="_blank" rel="noreferrer"><CalendarPlus size={15} /> Add calendar</a></div>{notice && <p className="classic-notice">{notice}</p>}</motion.form></ClassicSection>; }
