"use client";

import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring } from "framer-motion";
import { CalendarDays, Heart, MapPin, Pause, Play, Sparkles, X } from "lucide-react";
import { useRef, useState } from "react";
import { ScratchDateCard } from "./scratch-date-card";
import { DesignerFooter } from "./designer-footer";

type Event = { id: string; title: string; starts_at: string; venue_name: string | null; map_url: string | null };
type GalleryImage = { id: string; storage_path: string };
interface Props { brideName: string; groomName: string; weddingAt: string; venueName: string | null; invitationMessage: string | null; story: string | null; events: Event[]; coverImage: string | null; brideImage: string | null; groomImage: string | null; gallery: GalleryImage[]; musicUrl: string | null; mapUrl: string | null; brideOccupation: string | null; groomOccupation: string | null; brideParents: string | null; groomParents: string | null; brideBio: string | null; groomBio: string | null; familyInvitationMessage: string | null; }
const reveal = { hidden: { opacity: 0, y: 52, filter: "blur(8px)" }, visible: { opacity: 1, y: 0, filter: "blur(0px)" } };

export function HeritageInvitation(props: Props) {
  const [opened, setOpened] = useState(false); const [playing, setPlaying] = useState(false); const content = useRef<HTMLDivElement>(null); const audio = useRef<HTMLAudioElement>(null); const reduced = useReducedMotion(); const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 85, damping: 22 });
  const date = new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" }).format(new Date(props.weddingAt)); const time = new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(new Date(props.weddingAt));
  function open() { setOpened(true); if (props.musicUrl && audio.current?.paused) void audio.current.play(); setTimeout(() => content.current?.scrollIntoView({ behavior: "smooth" }), 160); }
  return <main className="min-h-screen overflow-hidden bg-[#fff8e9] text-[#6f2b20]"><motion.div className="fixed left-0 top-0 z-50 h-1 origin-left bg-gradient-to-r from-[#9c251d] via-[#e2af37] to-[#9c251d]" style={{ scaleX: progress }} /><div className="h-4 bg-[repeating-linear-gradient(90deg,#e87518_0_18px,#f4c836_18px_36px,#de5a21_36px_54px)]" />
    {props.musicUrl && <><audio loop onPause={() => setPlaying(false)} onPlay={() => setPlaying(true)} ref={audio} src={props.musicUrl} /><button aria-label="Music player" className="fixed bottom-5 right-5 z-40 grid h-11 w-11 place-items-center rounded-full border border-[#d9ad4b] bg-[#fff8e9] text-[#9f261d] shadow-lg transition hover:scale-110" onClick={() => audio.current?.paused ? void audio.current.play() : audio.current?.pause()}>{playing ? <Pause size={17} /> : <Play size={17} />}</button></>}
    <section className="relative grid min-h-[95svh] place-items-center px-6 py-20 text-center">{props.coverImage && <Image alt="Wedding celebration" className="absolute inset-0 object-cover opacity-20" fill priority sizes="100vw" src={props.coverImage} />}<div className="absolute inset-0 bg-[#fff8e9]/65" /><motion.div animate={reduced ? undefined : { rotate: 360 }} className="pointer-events-none absolute -right-20 top-14 h-64 w-64 rounded-full border-[28px] border-[#f7dd9f55]" transition={{ duration: 100, repeat: Infinity, ease: "linear" }} /><motion.div animate="visible" initial="hidden" transition={{ staggerChildren: .12 }} className="relative max-w-3xl"><motion.p variants={reveal} className="font-serif text-sm italic text-[#b67a29]">॥ Shubh Vivah ॥</motion.p><motion.div variants={reveal} className="mx-auto mt-7 flex w-fit items-center gap-3 text-[#d39a2d]"><span className="h-px w-12 bg-current" /><Sparkles size={16} /><span className="h-px w-12 bg-current" /></motion.div><motion.p variants={reveal} className="mt-10 text-xs font-semibold uppercase tracking-[.28em]">Together with the blessings of their families</motion.p><h1 className="mt-5 font-serif text-5xl leading-[.9] text-[#9a201b] sm:text-7xl"><Name name={props.brideName} /><motion.span animate={{ opacity: 1, rotate: 0 }} className="my-3 block text-3xl text-[#d39a2d]" initial={{ opacity: 0, rotate: -30 }} transition={{ delay: .7 }}>&amp;</motion.span><Name delay={.5} name={props.groomName} /></h1><motion.p variants={reveal} className="mx-auto mt-8 max-w-lg leading-8 text-[#77584b]">{props.invitationMessage || "Invite you to share in the joy, rituals, and warmth of their wedding celebration."}</motion.p><motion.button variants={reveal} className="mt-9 rounded-full bg-[#9c251d] px-7 py-4 text-xs font-bold uppercase tracking-[.18em] text-white shadow-lg transition hover:scale-105" onClick={open}>Open invitation</motion.button></motion.div></section>
    <AnimatePresence>{opened && <motion.div animate="visible" initial="hidden" ref={content} transition={{ staggerChildren: .12 }}><Reveal><ScratchDateCard date={date} /></Reveal><Reveal><section className="mx-auto max-w-5xl px-6 py-24 text-center"><Eyebrow>Our celebration</Eyebrow><h2 className="mt-4 font-serif text-4xl text-[#9a201b] sm:text-5xl">A beautiful beginning</h2><p className="mx-auto mt-6 max-w-2xl leading-8 text-[#77584b]">{props.story || "Every love story is beautiful. Ours is a celebration of family, friendship, tradition and the beginning of forever."}</p><div className="mt-16 grid gap-5 text-left md:grid-cols-2"><Card icon={<CalendarDays />} title="When" text={`${date} · ${time}`} /><Card icon={<MapPin />} title="Where" text={props.venueName || "Venue details coming soon"} /></div></section></Reveal>
    {(props.brideImage || props.groomImage) && <Reveal><section className="bg-[#fff3dc] px-6 py-24 text-center"><Eyebrow>The couple</Eyebrow><h2 className="mt-4 font-serif text-4xl text-[#9a201b] sm:text-5xl">Two hearts, one journey</h2><div className="mx-auto mt-11 grid max-w-4xl gap-7 sm:grid-cols-2">{props.brideImage && <Portrait image={props.brideImage} label={props.brideName} occupation={props.brideOccupation} parents={props.brideParents} bio={props.brideBio} />}{props.groomImage && <Portrait image={props.groomImage} label={props.groomName} occupation={props.groomOccupation} parents={props.groomParents} bio={props.groomBio} />}</div></section></Reveal>}
    {props.events.length > 0 && <Reveal><section className="border-y border-[#ecd8a9] bg-[#fff3dc] px-6 py-24"><div className="mx-auto max-w-5xl text-center"><Eyebrow>Celebrate with us</Eyebrow><h2 className="mt-4 font-serif text-4xl text-[#9a201b] sm:text-5xl">Wedding festivities</h2><div className="mt-11 grid gap-5 text-left md:grid-cols-2">{props.events.map((event, index) => <EventCard event={event} index={index} key={event.id} />)}</div></div></section></Reveal>}
    {props.gallery.length > 0 && <Reveal><Gallery images={props.gallery} /></Reveal>}
    {props.mapUrl && <Reveal><Map venueName={props.venueName} mapUrl={props.mapUrl} /></Reveal>}
    <Reveal><section className="border-y border-[#ecd8a9] bg-[#fff3dc] px-6 py-24 text-center"><Heart className="mx-auto text-[#c9472f]" fill="currentColor" size={19} /><p className="mx-auto mt-5 max-w-3xl font-serif text-3xl leading-relaxed text-[#9a201b]">{props.familyInvitationMessage || "With joyful hearts, our families invite you to bless this new beginning."}</p><DesignerFooter /></section></Reveal></motion.div>}</AnimatePresence></main>;
}
function Reveal({ children }: { children: React.ReactNode }) { const r = useReducedMotion(); return <motion.div variants={r ? undefined : reveal} transition={{ duration: 1.1, ease: [0.16, 1, 0.3, 1] }} viewport={{ once: true, amount: .13 }} whileInView="visible">{children}</motion.div>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-xs font-bold uppercase tracking-[.28em] text-[#b67a29]">{children}</p>; }
function Card({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <motion.article whileHover={{ y: -7, rotate: -.25 }} className="rounded-3xl border border-[#e8ce97] bg-[#fffaf0] p-8 shadow-[0_12px_28px_rgba(117,66,24,.08)]"><div className="text-[#c68d2b]">{icon}</div><p className="mt-6 font-serif text-3xl text-[#9a201b]">{title}</p><p className="mt-3 text-sm leading-6 text-[#77584b]">{text}</p></motion.article>; }
function Portrait({ image, label, occupation, parents, bio }: { image: string; label: string; occupation: string | null; parents: string | null; bio: string | null }) { return <motion.article whileHover={{ y: -8 }} className="overflow-hidden rounded-[2rem] border border-[#e7cb8f] bg-[#fffaf0] text-left shadow-[0_14px_30px_rgba(117,66,24,.12)]"><div className="relative aspect-[4/5] overflow-hidden"><Image alt={label} className="object-cover transition duration-700 hover:scale-105" fill sizes="(max-width: 640px) 100vw, 50vw" src={image} /></div><div className="p-6"><p className="font-serif text-3xl text-[#9a201b]">{label}</p>{occupation && <p className="mt-2 text-xs font-bold uppercase tracking-[.16em] text-[#b67a29]">{occupation}</p>}{parents && <p className="mt-4 text-sm text-[#77584b]">With love from {parents}</p>}{bio && <p className="mt-4 text-sm leading-7 text-[#77584b]">{bio}</p>}</div></motion.article>; }
function EventCard({ event, index }: { event: Event; index: number }) { return <motion.article initial={{ opacity: 0, y: 34 }} transition={{ delay: index * .1, duration: .75 }} viewport={{ once: true }} whileHover={{ y: -7, rotate: index % 2 ? .45 : -.45 }} whileInView={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-[#e7cb8f] bg-[#fff9ec] p-8 shadow-[0_12px_28px_rgba(117,66,24,.08)]"><span className="absolute -right-3 -top-9 font-serif text-9xl text-[#e9c97955]">{String(index + 1).padStart(2, "0")}</span><p className="relative font-serif text-3xl text-[#9a201b]">{event.title}</p><p className="relative mt-4 text-sm leading-6 text-[#77584b]">{new Intl.DateTimeFormat("en-IN", { dateStyle: "full", timeStyle: "short" }).format(new Date(event.starts_at))}</p>{event.venue_name && <p className="relative mt-2 text-sm text-[#77584b]">{event.venue_name}</p>}{event.map_url && <a className="relative mt-6 inline-block text-xs font-bold uppercase tracking-[.12em] text-[#9a201b] underline underline-offset-4" href={event.map_url} rel="noreferrer" target="_blank">Get directions</a>}</motion.article>; }
function Gallery({ images }: { images: GalleryImage[] }) { const [selected, setSelected] = useState<GalleryImage | null>(null); return <section className="mx-auto max-w-6xl px-6 py-24 text-center"><Eyebrow>Captured moments</Eyebrow><h2 className="mt-4 font-serif text-4xl text-[#9a201b] sm:text-5xl">A few of our favourites</h2><p className="mt-3 text-sm text-[#77584b]">Tap any memory to linger a little longer.</p><div className="mt-11 grid auto-rows-[150px] grid-cols-2 gap-4 sm:auto-rows-[220px] sm:grid-cols-4">{images.map((image, index) => <motion.button initial={{ opacity: 0, y: 34 }} transition={{ delay: index * .08, duration: .75 }} viewport={{ once: true }} whileHover={{ scale: 1.025 }} whileInView={{ opacity: 1, y: 0 }} className={`group relative overflow-hidden rounded-2xl shadow-md ${index % 5 === 0 ? "col-span-2 row-span-2" : index % 3 === 0 ? "row-span-2" : ""}`} key={image.id} onClick={() => setSelected(image)}><Image alt="Couple's captured moment" className="object-cover transition duration-700 group-hover:scale-110" fill sizes="(max-width: 640px) 50vw, 25vw" src={image.storage_path} /><span className="absolute inset-0 bg-gradient-to-t from-[#3c191380] via-transparent to-transparent opacity-0 transition group-hover:opacity-100" /><span className="absolute bottom-4 left-4 text-xs font-bold uppercase tracking-[.18em] text-white opacity-0 transition group-hover:opacity-100">View memory</span></motion.button>)}</div><AnimatePresence>{selected && <motion.div animate={{ opacity: 1 }} className="fixed inset-0 z-50 grid place-items-center bg-[#210f0bd9] p-5 backdrop-blur-sm" initial={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.div animate={{ scale: 1 }} initial={{ scale: .92 }} className="relative max-h-[90vh] max-w-4xl" onClick={(e) => e.stopPropagation()}><Image alt="Couple's captured moment" className="max-h-[85vh] w-auto rounded-2xl object-contain" height={1000} width={1200} src={selected.storage_path} /><button aria-label="Close image" className="absolute right-3 top-3 rounded-full bg-black/60 p-2 text-white" onClick={() => setSelected(null)}><X size={18} /></button></motion.div></motion.div>}</AnimatePresence></section>; }
function Map({ venueName, mapUrl }: { venueName: string | null; mapUrl: string }) { return <section className="bg-[#fff3dc] px-6 py-24 text-center"><Eyebrow>When & where</Eyebrow><h2 className="mt-4 font-serif text-4xl text-[#9a201b] sm:text-5xl">Find your way to us</h2><p className="mt-3 text-sm text-[#77584b]">{venueName || "Wedding venue"}</p><div className="mx-auto mt-10 max-w-3xl overflow-hidden rounded-3xl border border-[#e7cb8f] bg-white p-2 shadow-lg"><iframe className="h-80 w-full rounded-2xl grayscale-[.25] sepia-[.18]" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(venueName || mapUrl)}&output=embed`} title="Wedding venue map" /></div><a className="mt-5 inline-block rounded-full bg-[#9c251d] px-6 py-3 text-xs font-bold uppercase tracking-[.14em] text-white transition hover:scale-105" href={mapUrl} rel="noreferrer" target="_blank">Open directions</a></section>; }
function Name({ name, delay = 0 }: { name: string; delay?: number }) { return <span className="block">{Array.from(name).map((letter, i) => <motion.span animate={{ opacity: 1, y: 0, rotateX: 0 }} initial={{ opacity: 0, y: 34, rotateX: -80 }} key={`${letter}-${i}`} transition={{ delay: delay + i * .055, duration: .55, ease: [0.16, 1, 0.3, 1] }}>{letter === " " ? " " : letter}</motion.span>)}</span>; }
