"use client";

import { useActionState } from "react";
import { updateInvitation, type InvitationFormState } from "@/app/admin/actions";

const initialState: InvitationFormState = {};
export interface EditableInvitation { id: string; bride_name: string; groom_name: string; slug: string; wedding_at: string; venue_name: string | null; map_url: string | null; invitation_message: string | null; story: string | null; video_url: string | null; rsvp_email: string | null; whatsapp_number: string | null; bride_occupation: string | null; groom_occupation: string | null; bride_parents: string | null; groom_parents: string | null; bride_bio: string | null; groom_bio: string | null; family_invitation_message: string | null; theme_key: "classic" | "cinematic" | "heritage" | "royal"; }

export function EditInvitationForm({ invitation }: { invitation: EditableInvitation }) {
  const [state, action, isPending] = useActionState(updateInvitation, initialState);
  return <form action={action} className="mt-8 space-y-6" id="invitation-details-form"><input name="id" type="hidden" value={invitation.id} />
    <div className="grid gap-5 sm:grid-cols-2"><Field defaultValue={invitation.bride_name} label="Bride's name" name="brideName" required /><Field defaultValue={invitation.groom_name} label="Groom's name" name="groomName" required /></div>
    <Field defaultValue={new Date(invitation.wedding_at).toISOString().slice(0, 16)} label="Wedding date and time" name="weddingAt" required type="datetime-local" />
    <Field defaultValue={invitation.slug} hint="Lowercase words separated by hyphens" label="Website address" name="slug" required />
    <Field defaultValue={invitation.venue_name ?? ""} label="Venue" name="venueName" />
    <Field defaultValue={invitation.map_url ?? ""} label="Google Maps link" name="mapUrl" type="url" />
    <label className="block text-sm font-medium">Welcome message<textarea className="mt-2 min-h-28 w-full rounded-xl border border-stone-200 px-4 py-3" defaultValue={invitation.invitation_message ?? ""} name="invitationMessage" /></label>
    <label className="block text-sm font-medium">Their story or favourite quote<textarea className="mt-2 min-h-28 w-full rounded-xl border border-stone-200 px-4 py-3" defaultValue={invitation.story ?? ""} name="story" placeholder="A short note about their journey, or a meaningful quote." /></label>
    <Field defaultValue={invitation.video_url ?? ""} hint="YouTube links also create the Royal film and live-stream sections" label="Wedding film or live-stream link" name="videoUrl" type="url" />
    <section className="rounded-2xl border border-rose-100 bg-rose-50/40 p-5"><p className="font-semibold text-rose-900">Client contact & RSVP</p><p className="mt-1 text-sm text-stone-600">RSVPs are saved in the Vowcraft dashboard. Add the client&apos;s WhatsApp number to provide guests a direct contact option.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field defaultValue={invitation.rsvp_email ?? ""} label="Client RSVP email" name="rsvpEmail" type="email" /><Field defaultValue={invitation.whatsapp_number ?? ""} hint="Include country code, e.g. 919876543210" label="Client WhatsApp number" name="whatsappNumber" type="tel" /></div></section>
    <section className="rounded-2xl border border-rose-100 bg-rose-50/40 p-5"><p className="font-semibold text-rose-900">Bride&apos;s story</p><p className="mt-1 text-sm text-stone-600">Optional details that appear beside her portrait.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field defaultValue={invitation.bride_occupation ?? ""} label="Occupation" name="brideOccupation" /><Field defaultValue={invitation.bride_parents ?? ""} label="Parents&apos; names" name="brideParents" /></div><label className="mt-4 block text-sm font-medium">A few words about her<textarea className="mt-2 min-h-24 w-full rounded-xl border border-stone-200 px-4 py-3" defaultValue={invitation.bride_bio ?? ""} name="brideBio" placeholder="Her joy, her dreams, or a short personal introduction." /></label></section>
    <section className="rounded-2xl border border-rose-100 bg-rose-50/40 p-5"><p className="font-semibold text-rose-900">Groom&apos;s story</p><p className="mt-1 text-sm text-stone-600">Optional details that appear beside his portrait.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field defaultValue={invitation.groom_occupation ?? ""} label="Occupation" name="groomOccupation" /><Field defaultValue={invitation.groom_parents ?? ""} label="Parents&apos; names" name="groomParents" /></div><label className="mt-4 block text-sm font-medium">A few words about him<textarea className="mt-2 min-h-24 w-full rounded-xl border border-stone-200 px-4 py-3" defaultValue={invitation.groom_bio ?? ""} name="groomBio" placeholder="His character, passions, or a short personal introduction." /></label></section>
    <label className="block text-sm font-medium">Message from the families<textarea className="mt-2 min-h-28 w-full rounded-xl border border-stone-200 px-4 py-3" defaultValue={invitation.family_invitation_message ?? ""} name="familyInvitationMessage" placeholder="With immense joy, our families invite you to bless this new beginning…" /></label>
    <label className="block text-sm font-medium">Theme<select className="mt-2 w-full rounded-xl border border-stone-200 px-4 py-3" defaultValue={invitation.theme_key} name="themeKey"><option value="classic">Classic — warm and elegant</option><option value="cinematic">Cinematic Luxe — editorial and immersive</option><option value="heritage">Heritage Celebration — festive and traditional</option><option value="royal">Royal Premium — plum and gold luxury</option></select></label>
    {state.error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{state.error}</p>}<p className="text-sm text-stone-500">Use the Save all changes button at the bottom of this editor after updating these details.</p>
  </form>;
}

function Field({ label, name, hint, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; name: string; hint?: string }) { return <label className="block text-sm font-medium">{label}{hint && <span className="ml-2 text-xs font-normal text-stone-400">{hint}</span>}<input className="mt-2 w-full rounded-xl border border-stone-200 px-4 py-3" name={name} {...props} /></label>; }
